/**
 * Turns Natural Earth 110m country outlines into two flat SVG path strings,
 * projected with the same plate-carree formula the map uses, and writes them to
 * src/data/land.ts. Run once; the output is committed, so the app ships no
 * topojson dependency and does no projection work at runtime.
 *
 *   node scripts/build-map.mjs
 */
import fs from "node:fs";
import { createRequire } from "node:module";
import { merge, mesh } from "topojson-client";

const require = createRequire(import.meta.url);
const topo = require("world-atlas/countries-110m.json");

/* Must stay in step with mx()/my() in src/ui/map.ts. */
const MW = 1000;
const MH = 470;
const LAT_TOP = 78;
const LAT_SPAN = 156;
const px = (lon) => ((lon + 180) / 360) * MW;
const py = (lat) => ((LAT_TOP - lat) / LAT_SPAN) * MH;

const round = (n) => Math.round(n * 10) / 10;

/** Rings smaller than this in square units are dropped: unreadable specks. */
const MIN_AREA = 1.2;

function ringArea(ring) {
  let a = 0;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    a += ring[j][0] * ring[i][1] - ring[i][0] * ring[j][1];
  }
  return Math.abs(a / 2);
}

/** One ring of [lon,lat] pairs to "M…L…Z", dropping repeated points. */
function ringPath(ring, close) {
  const pts = [];
  let prev = null;
  for (const [lon, lat] of ring) {
    const p = [round(px(lon)), round(py(lat))];
    if (prev && p[0] === prev[0] && p[1] === prev[1]) continue;
    pts.push(p);
    prev = p;
  }
  if (pts.length < 2) return "";
  return (
    "M" + pts.map(([x, y]) => `${x} ${y}`).join("L") + (close ? "Z" : "")
  );
}

function geometryPath(geom, close) {
  const parts = [];
  const walk = (coords, depth) => {
    if (depth === 0) {
      const projected = coords.map(([lon, lat]) => [px(lon), py(lat)]);
      if (close && ringArea(projected) < MIN_AREA) return;
      const d = ringPath(coords, close);
      if (d) parts.push(d);
      return;
    }
    for (const c of coords) walk(c, depth - 1);
  };
  const depth = { LineString: 0, MultiLineString: 1, Polygon: 1, MultiPolygon: 2 }[
    geom.type
  ];
  walk(geom.coordinates, depth);
  return parts.join("");
}

const land = merge(topo, topo.objects.countries.geometries);
const borders = mesh(topo, topo.objects.countries, (a, b) => a !== b);

const LAND_PATH = geometryPath(land, true);
const BORDERS_PATH = geometryPath(borders, false);

const out = `/* Generated by scripts/build-map.mjs — do not edit by hand.
 * Natural Earth 110m country outlines (public domain), projected with the same
 * plate-carree formula as src/ui/map.ts: x = (lon+180)/360*${MW},
 * y = (${LAT_TOP}-lat)/${LAT_SPAN}*${MH}. Both maps reuse these paths under an
 * SVG transform, so the inset needs no second projection.
 */

/** Every landmass as one filled path, islands under ${MIN_AREA} sq units dropped. */
export const LAND_PATH =
  ${JSON.stringify(LAND_PATH)};

/** Country borders only — coastlines are already the edge of LAND_PATH. */
export const BORDERS_PATH =
  ${JSON.stringify(BORDERS_PATH)};
`;
fs.writeFileSync("src/data/land.ts", out);

const kb = (s) => (s.length / 1024).toFixed(1) + " KB";
console.log(`land:    ${kb(LAND_PATH)}  (${(LAND_PATH.match(/M/g) || []).length} rings)`);
console.log(`borders: ${kb(BORDERS_PATH)}  (${(BORDERS_PATH.match(/M/g) || []).length} lines)`);
console.log(`file:    ${kb(out)}`);
