/**
 * Builds the /quiz question bank: each country with its capital and a pool of
 * its own largest cities to draw wrong answers from.
 *
 *   node scripts/build-quiz.mjs
 *
 * Distractors are other cities in the same country, taken largest first, which
 * is what makes the question worth asking — "Paris, Marseille, Lyon, Toulouse"
 * is a real question, "Paris" against three villages is not.
 */
import fs from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const world = require("world-countries");
const cities = require("all-the-cities");

/** How many alternatives to keep per country; three are shown at a time. */
const POOL = 7;

/** The seven-continent model, from ISO region plus subregion. */
function continentOf(c) {
  if (c.region === "Americas") {
    return c.subregion === "South America" ? "South America" : "North America";
  }
  return c.region;
}

/** Also the order they are offered in on the page. */
const KEEP = ["Asia", "Europe", "Africa", "North America", "South America", "Oceania"];

const norm = (s) =>
  s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z]/g, "");

/**
 * Cities that are a seat of government without being the listed capital. A
 * question is only fair if exactly one option is right, and "Bolivia: Sucre or
 * La Paz?" has two defensible answers — La Paz is where the government sits.
 */
const OTHER_SEATS = {
  Bolivia: ["La Paz"],
  Netherlands: ["The Hague"],
  Tanzania: ["Dar es Salaam"],
  "Ivory Coast": ["Abidjan"],
  Benin: ["Cotonou"],
  "Sri Lanka": ["Sri Jayawardenepura Kotte", "Colombo"],
  Eswatini: ["Lobamba", "Mbabane"],
  Malaysia: ["Putrajaya"],
  Chile: ["Valparaíso"],
  Montenegro: ["Cetinje"],
  Burundi: ["Bujumbura"],
  Nigeria: [],
};

const byCountry = new Map();
for (const c of cities) {
  if (!byCountry.has(c.country)) byCountry.set(c.country, []);
  byCountry.get(c.country).push(c);
}

const rows = [];
const skipped = [];
for (const c of world) {
  if (!c.independent || !c.capital || !c.capital.length) continue;
  const continent = continentOf(c);
  if (!KEEP.includes(continent)) continue;

  const capital = c.capital[0];
  const capNames = new Set([
    ...c.capital.map(norm),
    ...(OTHER_SEATS[c.name.common] ?? []).map(norm),
  ]);

  const pool = (byCountry.get(c.cca2) ?? [])
    /* PPLC is the country's own capital; excluding it by code as well as by
       name catches the cases where the two datasets spell it differently. */
    .filter((x) => {
      if (x.featureCode === "PPLC") return false;
      const n = norm(x.name);
      /* Also drop anything that contains the capital or is contained by it:
         "Delhi" must not be offered against the answer "New Delhi". */
      return ![...capNames].some((cap) => n === cap || n.includes(cap) || cap.includes(n));
    })
    .sort((a, b) => b.population - a.population)
    .map((x) => x.name);

  const seen = new Set();
  const distractors = pool.filter((n) => {
    const k = norm(n);
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  }).slice(0, POOL);

  if (distractors.length < 3) {
    skipped.push(`${c.name.common} (${distractors.length})`);
    continue;
  }
  rows.push({ n: c.name.common, c: continent, a: capital, d: distractors });
}

rows.sort((a, b) => a.n.localeCompare(b.n));

const counts = {};
for (const r of rows) counts[r.c] = (counts[r.c] ?? 0) + 1;

const out = `/* Generated by scripts/build-quiz.mjs — do not edit by hand.
 * Capitals from world-countries (ISO 3166-1); wrong answers are that same
 * country's next largest cities, from all-the-cities.
 */

export interface Question {
  /** Country name. */
  n: string;
  /** Continent, seven-continent model. */
  c: Continent;
  /** The capital: the correct answer. */
  a: string;
  /** That country's other largest cities, to draw wrong answers from. */
  d: string[];
}

export const CONTINENTS = [
${KEEP.filter((k) => counts[k]).map((k) => `  ${JSON.stringify(k)},`).join("\n")}
] as const;

export type Continent = (typeof CONTINENTS)[number];

export const QUESTIONS: Question[] = ${JSON.stringify(rows, null, 0)
  .replace(/\},\{/g, "},\n  {")
  .replace(/^\[/, "[\n  ")
  .replace(/\]$/, ",\n]")};
`;
fs.writeFileSync("src/data/quiz.ts", out);

console.log(`questions:  ${rows.length}`);
console.log(`by continent: ${Object.entries(counts).map(([k, v]) => `${k} ${v}`).join(", ")}`);
console.log(`file:       ${(out.length / 1024).toFixed(0)} KB`);
console.log(`skipped (too few cities of their own): ${skipped.length} — ${skipped.join(", ")}`);
